from . import product_supplierinfo_historic
from . import purchase_promotion
from . import product_supplierinfo_inherit
from . import stock_move_inherit
from . import stock_move_line_inherit
from . import purchase_order_inherit
from . import purchase_order_line_inherit
from . import product_packaging_inherit
from . import account_invoice_line_inherit